# Permalinks
permalink:           pretty

# Setup
title:               Regan Gully
tagline:             Software Engineer & Designer
url:                 https://regangully.com
paginate:            10
paginate_path:      ""
paginate_path:      "blog/page:num"
baseurl:             ""

defaults:
  - scope:
      path: "_assets/img"
    values:
      image: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Regan Gully
  url:               https://regangully.com/
  email:             gullyregan@gmail.com

# Custom vars
version:             3.0.1
github:
  repo:              https://github.com/regangully/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
